version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '20241008'
      MYSQL_DATABASE: app_database
      MYSQL_USER: user
      MYSQL_PASSWORD: '20241008'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./web
    command: bundle exec rails server -p 8080 -b '0.0.0.0'
    volumes:
      - ./web:/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: '20241008'
      DATABASE_NAME: app_database

  php:
    build: ./php
    volumes:
      - ./php:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8060:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '20241008'
    depends_on:
      - db

  node:
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  db_data:
